In [ ]:
print('dd')

dd


In [ ]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA Available:", torch.cuda.is_available())
print("Device:", "CUDA (GPU)" if torch.cuda.is_available() else "CPU")


PyTorch version: 2.6.0+cu124
CUDA Available: True
Device: CUDA (GPU)


In [ ]:
!nvidia-smi

Mon Jun 16 03:29:05 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   45C    P8              9W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [10]:
x=torch.rand(3,3)
print(x)
y=torch.rand(3,3)
print(x)
z=x+y
print("x+y:",z)

tensor([[0.8690, 0.8898, 0.5277],
        [0.3590, 0.7992, 0.3203],
        [0.4260, 0.6906, 0.2084]])
tensor([[0.8690, 0.8898, 0.5277],
        [0.3590, 0.7992, 0.3203],
        [0.4260, 0.6906, 0.2084]])
x+y: tensor([[1.2016, 1.0408, 0.7162],
        [1.3400, 0.8858, 1.0592],
        [1.3846, 0.9950, 0.9034]])


In [11]:
import torch
print(torch.cuda.is_available())


True


In [13]:
x=torch.empty(1)
x
#torch.empty(1) মানে কী?
#👉 এটা একটি PyTorch tensor তৈরি করে যার সাইজ হচ্ছে 1, অর্থাৎ একটি এলিমেন্ট আছে।

#⚠️ কিন্তু "empty" মানে হলো:
##শুধু shape তৈরি হবে, কিন্তু ভেতরের মান (value) প্রাকৃতিকভাবে undefined / garbage হবে।

#মানে: এটা random value দিবে (কিন্তু সেটা noise/random হবার কথা), কারণ কোনো initialization হয় না।

tensor([7.7260e-11])

In [14]:
x=torch.empty(2,3)
print(x)

tensor([[1.4013e-45, 0.0000e+00, 3.5873e-43],
        [0.0000e+00, 7.3747e-27, 4.3524e-41]])


In [17]:
x=torch.empty(2,3,3) #3d matrix
x

tensor([[[2.1707e-18, 7.0952e+22, 1.7748e+28],
         [1.8176e+31, 7.2708e+31, 5.0778e+31],
         [3.2608e-12, 1.7728e+28, 7.0367e+22]],

        [[2.1715e-18, 8.1995e-10, 2.7476e-06],
         [1.0558e-08, 4.1951e-08, 7.9959e+20],
         [1.0413e-11, 1.0559e-08, 2.1391e+23]]])

In [18]:
x.size()

torch.Size([2, 3, 3])

In [19]:
x.shape

torch.Size([2, 3, 3])

In [20]:
x.ndim

3

In [21]:
x=torch.zeros(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [24]:
x=torch.ones(2,3)
print(x)
print(x.ndim)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
2


In [25]:
x=torch.full((2,3,2),fill_value=7)
print(x)
print(x.ndim)

tensor([[[7, 7],
         [7, 7],
         [7, 7]],

        [[7, 7],
         [7, 7],
         [7, 7]]])
3


In [26]:
x=torch.full((2,4),fill_value=9,dtype=torch.float)
print(x)
print(x.ndim)

tensor([[9., 9., 9., 9.],
        [9., 9., 9., 9.]])
2


In [27]:
x=torch.empty(2,3,2,dtype=torch.double)
print(x)

tensor([[[3.8735e-315, 3.8738e-315],
         [3.1620e-322, 3.9525e-322],
         [3.8747e-315, 3.9268e+126]],

        [[4.2522e+180, 7.4854e+247],
         [2.3236e+251, 6.1113e+223],
         [2.5990e-144,  1.6687e-47]]], dtype=torch.float64)


In [28]:
x=torch.tensor([24,3.4,5.6])
x

tensor([24.0000,  3.4000,  5.6000])

In [32]:
x=torch.rand(2,2)
y=torch.rand(2,2)
z=x+y
print(x)
print(y)
print("x+y",z)
s=torch.add(x,y)
print("x+y:",s)
y.add_(x)
print('x+y:',y)


tensor([[0.3105, 0.4846],
        [0.6904, 0.0147]])
tensor([[0.7447, 0.0501],
        [0.6941, 0.5948]])
x+y tensor([[1.0552, 0.5346],
        [1.3845, 0.6095]])
x+y: tensor([[1.0552, 0.5346],
        [1.3845, 0.6095]])
x+y: tensor([[1.0552, 0.5346],
        [1.3845, 0.6095]])


In [33]:
d=x-y
print("substarct:",d)
s=torch.sub(x,y)
print(s)
x.sub_(y)
print(x)


substarct: tensor([[-0.7447, -0.0501],
        [-0.6941, -0.5948]])
tensor([[-0.7447, -0.0501],
        [-0.6941, -0.5948]])
tensor([[-0.7447, -0.0501],
        [-0.6941, -0.5948]])


In [35]:
d=x*y
print(d)
s=torch.mul(x,y)
x.mul_(y)
print(s)
print(x)

tensor([[-0.8292, -0.0143],
        [-1.3304, -0.2209]])
tensor([[-0.8292, -0.0143],
        [-1.3304, -0.2209]])
tensor([[-0.8292, -0.0143],
        [-1.3304, -0.2209]])


In [36]:
s=x/y
print(s)
d=torch.div(x,y)
print(d)
x.div_(y)
print(x)

tensor([[-0.7858, -0.0268],
        [-0.9609, -0.3625]])
tensor([[-0.7858, -0.0268],
        [-0.9609, -0.3625]])
tensor([[-0.7858, -0.0268],
        [-0.9609, -0.3625]])


In [41]:
#view mane hsse reshapr ekorbe
x=torch.rand(4,4)
print(x)
print()
y=x.view(16)
print(y)
print(x.ndim)
print(y.ndim)

tensor([[0.7696, 0.1167, 0.3846, 0.6715],
        [0.7665, 0.6254, 0.8505, 0.2890],
        [0.1991, 0.3894, 0.6223, 0.5413],
        [0.1105, 0.8892, 0.4146, 0.2319]])

tensor([0.7696, 0.1167, 0.3846, 0.6715, 0.7665, 0.6254, 0.8505, 0.2890, 0.1991,
        0.3894, 0.6223, 0.5413, 0.1105, 0.8892, 0.4146, 0.2319])
2
1


In [43]:
y=x.view(2,8)
print(y)
print(y.ndim)

tensor([[0.7696, 0.1167, 0.3846, 0.6715, 0.7665, 0.6254, 0.8505, 0.2890],
        [0.1991, 0.3894, 0.6223, 0.5413, 0.1105, 0.8892, 0.4146, 0.2319]])
2


In [47]:
#tensor to numpy array, a te ja thakbe b teo tai , a te cng b teo cng hbe auto
a=torch.ones(5)
print(a)
b=a.numpy()
print(type(b))
print(b)

a.add_(1) #a te add krsi , b teo auto add hye jabe
print("a+b",a)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]
a+b tensor([2., 2., 2., 2., 2.])


In [53]:
import numpy as np
a=np.ones(5)
print("Numpy:",a)
print()
b=torch.from_numpy(a)
print(b)
a+=1;
print(a) # numpy a add korlam ,, tensor ao ad hoye gelo auto
print()
print(b)

Numpy: [1. 1. 1. 1. 1.]

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [60]:
import torch  # PyTorch লাইব্রেরি ইমপোর্ট

# চেক করো GPU (CUDA) অ্যাভেইলেবল আছে কি না
if torch.cuda.is_available():

    # "cuda" ডিভাইস বানানো (মানে GPU)
    device = torch.device("cuda")

    # GPU তে ৫টা ১ (one) দিয়ে tensor তৈরি
    x = torch.ones(5, device=device)

    # CPU তে ৫টা ১ দিয়ে tensor তৈরি
    y = torch.ones(5)

    # y কে GPU তে পাঠানো
    y = y.to(device)

    # x আর y এর যোগফল — কাজটা GPU তেই হবে
    z = x + y

    # z কে আবার CPU তে ফেরত আনা (প্রিন্ট করার জন্য)
    z = z.to("cpu")

    # রেজাল্ট প্রিন্ট
    print(z)

else:
    # যদি GPU না থাকে, এই মেসেজ দেখাও
    print("Not")


tensor([2., 2., 2., 2., 2.])


In [62]:
#Autograde
x=torch.ones(5,requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


 requires_grad=True
এই অপশনটা দিলে PyTorch জানে — "এই tensor এর উপর যেই সব অপারেশন হবে, তার gradient হিসেব রাখতে হবে।"

📌 অর্থাৎ:

এই x থেকে যদি তুমি কোনো ফাংশন তৈরি করো (যেমন y = x.sum()), তাহলে .backward() দিলে PyTorch gradient বের করতে পারবে।

🔎 Output:

In [66]:
x = torch.ones(5, requires_grad=True)   # Gradient track করবো
y = x * 2                               # y = [2, 2, 2, 2, 2]
z = y.sum()                             # z = 2 + 2 + 2 + 2 + 2 = 10
z.backward()
                      # Gradient হিসাব শুরু

print(x.grad)   # dx = ∂z/∂x = 2


tensor([2., 2., 2., 2., 2.])


ব্যাখ্যা (Step by Step):
🧮 ১. x = [1, 1, 1, 1, 1]
🧮 ২. y = x * 2 = [2, 2, 2, 2, 2]
➡️ এখানে y হলো x এর উপর একটা ফাংশন: y = 2x

🧮 ৩. z = y.sum()
➡️ z = 2x₁ + 2x₂ + 2x₃ + 2x₄ + 2x₅ = 10

In [67]:
import torch

# Step 1: টেন্সর বানাও এবং gradient ট্র্যাকিং চালু করো
x = torch.tensor([2.0], requires_grad=True)

# Step 2: ফাংশন হিসাব করো → f(x) = x^3 + 2x
y = x**3 + 2*x

# Step 3: Gradient বের করো
y.backward()

# Step 4: Gradient প্রিন্ট করো
print("x =", x.item())
print("y =", y.item())
print("Gradient dy/dx =", x.grad.item())


x = 2.0
y = 12.0
Gradient dy/dx = 14.0


Gradient মানে হলো derivative — যেকোনো ফাংশন কতটা পরিবর্তন হয় একটা ইনপুট বদলালে।

সোজা কথায়:

তুমি y = f(x) জানো।

তাহলে gradient (∂y/∂x) = x বাড়লে, y কত বাড়ে/কমে — এই হিসাব।

PyTorch কিভাবে gradient বের করে?
➡️ তুমি যদি কোন tensor বানাও requires_grad=True দিয়ে,
➡️ তারপর তার উপর কিছু operations করো (addition, multiplication ইত্যাদি),
➡️ শেষে .backward() চালাও, তাহলে PyTorch gradient auto calculate করে।

In [80]:
x=torch.randn(3,requires_grad=True)
print(x)
y=x+2
print(y)
z=y*y*2
print(z)
#z=z.mean()
print(z)
v=torch.tensor([0.1,1.0,0.001],dtype=torch.float32)
z.backward(v)  #dz/dx
print(x.grad)




tensor([-1.5121, -0.4892,  1.9013], requires_grad=True)
tensor([0.4879, 1.5108, 3.9013], grad_fn=<AddBackward0>)
tensor([ 0.4761,  4.5648, 30.4410], grad_fn=<MulBackward0>)
tensor([ 0.4761,  4.5648, 30.4410], grad_fn=<MulBackward0>)
tensor([0.1952, 6.0430, 0.0156])


In [85]:
# 3 ways for stop gradient function
x=torch.randn(3,requires_grad=True)
print(x)
print()
x.requires_grad=False
print(x)

y=x.detach()
print(y)

with torch.no_grad():
  z=x
  print(z)

tensor([ 0.5957, -1.6221, -0.7021], requires_grad=True)

tensor([ 0.5957, -1.6221, -0.7021])
tensor([ 0.5957, -1.6221, -0.7021])
tensor([ 0.5957, -1.6221, -0.7021])



x.requires_grad = False
✅ এটা existing tensor এর উপর সরাসরি gradient tracking off করে দেয়।
অর্থাৎ এখন থেকে x এর উপর কোনো অপারেশন করলে PyTorch আর gradient হিসাব রাখবে না।

📌 কখন ব্যবহার করবো?
যখন তোমার কাছে আগেই একটা tensor আছে যার জন্য গ্র‍্যাডিয়েন্ট track হচ্ছিল, কিন্তু এখন সেটা fixed বা inference mode-এ ব্যবহার করতে চাও।


y = x.detach()
✅ এটা x টেন্সরের একটা কপি বানায় যেটা computational graph থেকে পুরোপুরি আলাদা।
➡️ এর মানে y-এর উপর যেই অপারেশনই করো না কেন, PyTorch ধরে নেবে: "এটা কোনো gradient-calculable chain-এর অংশ না"।

📌 কখন ব্যবহার করবো?
যখন একটা tensor থেকে gradient tracking ছাড়াই output বের করতে চাও, কিন্তু x কে মূলত অপরিবর্তিত রাখতেও চাও।


with torch.no_grad():
    z = x
✅ এটা একটা context block — এর ভেতরে সব টেন্সরের উপর অপারেশন PyTorch gradient হিসাব করবে না।

📌 কখন ব্যবহার করবো?
যখন model evaluation বা prediction করো (inference time), তখন পুরো ব্লকেই gradient tracking বন্ধ করে efficient computation করতে চাও।



In [91]:
weights=torch.ones(4,requires_grad=True)
for epoch in range(4):
  model_output=(weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [93]:
import torch

weights = torch.ones(4, requires_grad=True)
optimizer = torch.optim.SGD([weights], lr=0.01)

# Forward pass
output = (weights * 2).sum()

# Backward pass
output.backward()

# Gradient descent step
optimizer.step()

# Zero out gradients
optimizer.zero_grad()

print(weights)  # You’ll see weights have been updated slightly


tensor([0.9800, 0.9800, 0.9800, 0.9800], requires_grad=True)
