In [ ]:
#18/06/2025
#Tamim Mahmud from Daffodil International University
#PyTorch DataLoader
import torch

PyTorch-er DataLoader ta Deep Learning-e dataset ke efficiently load korte use hoy, especially jokhon amra large dataset niye kaaj kori.


PyTorch-e model train korar jonno dataset ke small batches-e divide kore load kora hoy — eta kore DataLoader.

Main kaj gulo:

--Dataset ke batch kore

--Shuffling kore (training-e randomness er jonno)

--Parallel loading (faster dataset loading)

**Dataset → DataLoader

PyTorch-e DataLoader use korar age amader ekta Dataset class thakte hoy


In [ ]:
from torch.utils.data import Dataset

class MyDataset(Dataset):
  def __init__(self):
    self.data=[i for i in range(100)]

  def __len__(self):
    return len(self.data)

  def __getitem__(self,idx):
    return self.data[idx]

2. DataLoader Create kora

In [ ]:
from torch.utils.data import DataLoader

dataset=MyDataset()
loader=DataLoader(dataset,batch_size=10,shuffle=True)

#batch_size=10: Protibar 10 ta kore data dibe

#shuffle=True: Random order-e dibe

3.Loop diye data access

In [ ]:
for batch in loader:
  print(batch)
#Protibar batch er moddhe 10 ta element thakbe (jodi batch_size 10 hoy).

tensor([71, 72, 67, 43, 53, 20, 57, 98, 30,  9])
tensor([76, 62, 11, 51,  7, 55, 48, 39, 15, 60])
tensor([85, 27, 97, 66, 90, 17, 31, 37, 64, 93])
tensor([ 0, 94, 24, 36, 32, 77, 83, 49, 25, 79])
tensor([42, 28, 56, 91,  1, 45, 41, 38, 61, 69])
tensor([58, 14, 50, 73, 95, 88, 46,  5,  4, 63])
tensor([ 8, 99, 34, 96, 47, 52, 59, 18, 86, 82])
tensor([87, 54, 78, 80, 40, 68, 13, 75, 22, 29])
tensor([10, 26, 16, 19, 81, 35, 65, 21, 44, 23])
tensor([74, 84,  2, 92, 89,  6, 33,  3, 70, 12])


In [ ]:
#full code with dummy data
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

class Tamim (Dataset):
  def __init__(self):
    self.data=[i for i in range(100)]

  def __len__(self):
    return len(self.data)

  def __getitem__(self,idx):
    return self.data[idx]

dataset=Tamim()

loader=DataLoader(dataset,batch_size=8,shuffle=True)

for batch in loader:
  print(batch)


tensor([76, 54, 99, 59, 85, 90, 47, 74])
tensor([38, 93, 67, 44, 35, 62, 30, 91])
tensor([14,  0, 96, 80, 31,  2, 41, 28])
tensor([11,  8, 83, 24, 88, 17, 81, 27])
tensor([60, 21, 33,  3, 10, 26, 63, 84])
tensor([89, 66, 49, 57, 94, 48, 18, 82])
tensor([55,  6, 68,  7, 12, 36, 34, 69])
tensor([15, 23, 46, 56, 79, 98, 16, 64])
tensor([13, 52,  5, 42, 53, 58, 75, 70])
tensor([39, 72, 37, 20, 92, 51,  1, 43])
tensor([22, 78,  9, 71, 86,  4, 50, 25])
tensor([45, 65, 61, 19, 29, 77, 97, 40])
tensor([32, 73, 95, 87])


In [18]:
from google.colab import files
uploaded = files.upload()


Saving wine.csv to wine.csv


In [19]:
!ls


sample_data  wine.csv


In [ ]:
# from Petric Loaber


In [ ]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

# gradient computation etc. not efficient for whole data set
# -> divide dataset into small batches

'''
# training loop
for epoch in range(num_epochs):
    # loop over all batches
    for i in range(total_batches):
        batch_x, batch_y = ...
'''

# epoch = one forward and backward pass of ALL training samples
# batch_size = number of training samples used in one forward/backward pass
# number of iterations = number of passes, each pass (forward+backward) using [batch_size] number of sampes
# e.g : 100 samples, batch_size=20 -> 100/20=5 iterations for 1 epoch

# --> DataLoader can do the batch computation for us

# Implement a custom Dataset:
# inherit Dataset
# implement __init__ , __getitem__ , and __len__

class WineDataset(Dataset):

    def __init__(self):
        # Initialize data, download, etc.
        # read with numpy or pandas
        xy = np.loadtxt('wine.csv', delimiter=',', dtype=np.float32, skiprows=1)
        self.n_samples = xy.shape[0]

        # here the first column is the class label, the rest are the features
        self.x_data = torch.from_numpy(xy[:, 1:]) # size [n_samples, n_features]
        self.y_data = torch.from_numpy(xy[:, [0]]) # size [n_samples, 1]

    # support indexing such that dataset[i] can be used to get i-th sample
    def __getitem__(self, index):
        return self.x_data[index], self.y_data[index]

    # we can call len(dataset) to return the size
    def __len__(self):
        return self.n_samples


# create dataset
dataset = WineDataset()

# get first sample and unpack
first_data = dataset[0]
features, labels = first_data
print(features, labels)

# Load whole dataset with DataLoader
# shuffle: shuffle data, good for training
# num_workers: faster loading with multiple subprocesses
# !!! IF YOU GET AN ERROR DURING LOADING, SET num_workers TO 0 !!!
train_loader = DataLoader(dataset=dataset,
                          batch_size=4,
                          shuffle=True,
                          num_workers=2)

# convert to an iterator and look at one random sample
dataiter = iter(train_loader)
data = next(dataiter)
features, labels = data
print(features, labels)

# Dummy Training loop
num_epochs = 2
total_samples = len(dataset)
n_iterations = math.ceil(total_samples/4)
print(total_samples, n_iterations)
for epoch in range(num_epochs):
    for i, (inputs, labels) in enumerate(train_loader):

        # here: 178 samples, batch_size = 4, n_iters=178/4=44.5 -> 45 iterations
        # Run your training process
        if (i+1) % 5 == 0:
            print(f'Epoch: {epoch+1}/{num_epochs}, Step {i+1}/{n_iterations}| Inputs {inputs.shape} | Labels {labels.shape}')

# some famous datasets are available in torchvision.datasets
# e.g. MNIST, Fashion-MNIST, CIFAR10, COCO

train_dataset = torchvision.datasets.MNIST(root='./data',
                                           train=True,
                                           transform=torchvision.transforms.ToTensor(),
                                           download=True)

train_loader = DataLoader(dataset=train_dataset,
                                           batch_size=3,
                                           shuffle=True)

# look at one random sample
dataiter = iter(train_loader)
data = next(dataiter)
inputs, targets = data
print(inputs.shape, targets.shape)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])
tensor([[1.1660e+01, 1.8800e+00, 1.9200e+00, 1.6000e+01, 9.7000e+01, 1.6100e+00,
         1.5700e+00, 3.4000e-01, 1.1500e+00, 3.8000e+00, 1.2300e+00, 2.1400e+00,
         4.2800e+02],
        [1.2860e+01, 1.3500e+00, 2.3200e+00, 1.8000e+01, 1.2200e+02, 1.5100e+00,
         1.2500e+00, 2.1000e-01, 9.4000e-01, 4.1000e+00, 7.6000e-01, 1.2900e+00,
         6.3000e+02],
        [1.2930e+01, 3.8000e+00, 2.6500e+00, 1.8600e+01, 1.0200e+02, 2.4100e+00,
         2.4100e+00, 2.5000e-01, 1.9800e+00, 4.5000e+00, 1.0300e+00, 3.5200e+00,
         7.7000e+02],
        [1.2420e+01, 4.4300e+00, 2.7300e+00, 2.6500e+01, 1.0200e+02, 2.2000e+00,
         2.1300e+00, 4.3000e-01, 1.7100e+00, 2.0800e+00, 9.2000e-01, 3.1200e+00,
         3.6500e+02]]) tensor([[2.],
        [3.],
        [1.],
        [2.]])
178 45
Epoch

In [13]:
class Tamim(Dataset):
  def __init__(self):
     # Dummy data: features and labels
        self.X = torch.tensor([[1.0], [2.0], [3.0], [4.0], [5.0]])
        self.y = torch.tensor([[2.0], [4.0], [6.0], [8.0], [10.0]])
  def __len__(self):
    return len(self.X)

  def __getitem__(self,idx):
    return self.X[idx],self.y[idx]

dataset=Tamim()

dataload=DataLoader(dataset,batch_size=4,shuffle=True)

for i in dataload:
  print (i)

[tensor([[1.],
        [4.],
        [2.],
        [5.]]), tensor([[ 2.],
        [ 8.],
        [ 4.],
        [10.]])]
[tensor([[3.]]), tensor([[6.]])]


In [31]:
import torch
import torchvision
from torch.utils.data import Dataset,DataLoader
import numpy as np
import math

class WineDataset(Dataset):
  def __init__(self):
    xy=np.loadtxt('wine.csv',delimiter=',',dtype=np.float32,skiprows=1)
    self.x_data=torch.from_numpy(xy[:,1:])
    self.y_data=torch.from_numpy(xy[:, [0]])
    self.n_samples=xy.shape[0]

  def __len__(self):
    return self.n_samples

  def __getitem__(self,idx):
    return self.x_data[idx], self.y_data[idx]

dataset=WineDataset()
first_data=dataset[0]
features,labels=first_data
print(features,labels)

train_loader=DataLoader(dataset=dataset,batch_size=4,shuffle=True,num_workers=2)


dataiter=iter(train_loader)
data=next(dataiter)
features,labels=data
print(features,labels)
#Iterator বানিয়ে, প্রথম batch-এর features আর labels দেখা হচ্ছে

num_epochs = 2

total_samples=len(dataset)
n_iterations=math.ceil(total_samples/4)

for epoch in range(num_epochs):
    for i, (inputs, labels) in enumerate(train_loader):
        if (i+1) % 5 == 0:
            print(f'Epoch: {epoch+1}/{num_epochs}, Step {i+1}/{n_iterations}| Inputs {inputs.shape} | Labels {labels.shape}')
train_dataset = torchvision.datasets.MNIST(
    root='./data',
    train=True,
    transform=torchvision.transforms.ToTensor(),
    download=True)
train_loader = DataLoader(dataset=train_dataset,
                          batch_size=3,
                          shuffle=True)

dataiter = iter(train_loader)
data = next(dataiter)
inputs, targets = data
print(inputs.shape, targets.shape)


tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])
tensor([[1.3450e+01, 3.7000e+00, 2.6000e+00, 2.3000e+01, 1.1100e+02, 1.7000e+00,
         9.2000e-01, 4.3000e-01, 1.4600e+00, 1.0680e+01, 8.5000e-01, 1.5600e+00,
         6.9500e+02],
        [1.3290e+01, 1.9700e+00, 2.6800e+00, 1.6800e+01, 1.0200e+02, 3.0000e+00,
         3.2300e+00, 3.1000e-01, 1.6600e+00, 6.0000e+00, 1.0700e+00, 2.8400e+00,
         1.2700e+03],
        [1.4380e+01, 3.5900e+00, 2.2800e+00, 1.6000e+01, 1.0200e+02, 3.2500e+00,
         3.1700e+00, 2.7000e-01, 2.1900e+00, 4.9000e+00, 1.0400e+00, 3.4400e+00,
         1.0650e+03],
        [1.1030e+01, 1.5100e+00, 2.2000e+00, 2.1500e+01, 8.5000e+01, 2.4600e+00,
         2.1700e+00, 5.2000e-01, 2.0100e+00, 1.9000e+00, 1.7100e+00, 2.8700e+00,
         4.0700e+02]]) tensor([[3.],
        [1.],
        [1.],
        [2.]])
Epoch: 1/2, 

100%|██████████| 9.91M/9.91M [00:00<00:00, 17.8MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 478kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 4.44MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 6.52MB/s]


torch.Size([3, 1, 28, 28]) torch.Size([3])
